### ISSUE TITLE
Fix some stuff

### ISSUE THREAD

**Issue by Zsl8** [Aijazmakerb/vidsrc-api#2]
i was able to fix some problems in this project using burpsuite proxi but i'm still having a problem i'm getting 404 in the 
`https://vidplay.online/mediainfo/`
request
if you could fix it or give me the request requirements i'll be gratefull 

all i did chage the domain from `vidplay.site` to `vidplay.online`

**Comment by Tommy0412** [comment]
Use this key extractor https://raw.githubusercontent.com/Ciarands/vidsrc-keys/main/keys.json and add some headers for example useragent too avoid detection

**Comment by Zsl8** [comment]
> Use this key extractor https://raw.githubusercontent.com/Ciarands/vidsrc-keys/main/keys.json and add some headers for example useragent too avoid detection

alredy using it but still getting 404 in the response 

```js
const response = await axios.get(`https://vidplay.online/mediainfo/${data}?${vidplayLink.split('?')[1]}&autostart=true`, {
        params: {
            v: Date.now().toString(),
        },
        headers: {
            "Referer": vidplayLink
        }
    });
```

**Comment by Tommy0412** [comment]
> ```js
> axios.get
> ```

im using it on vps and onrender and it work fine, i need to restart it every day since it crash but it work most of times just fine, where you hosting it on vps, versel render? maybe they ban your ip adress so axios cant get it, add User-Agent header or use proxy.

**Comment by Aijazmakerb** [comment]
Thanks for raising the issue, i was inactive because of my busy schedule but now this project is working fine
