### ISSUE TITLE
Decrypt key ussue

### ISSUE THREAD

**Issue by rahuloberai** [Aijazmakerb/vidsrc-api#3]
Cany you please check the decrypt key '8z5Ag5wgagfsOuhz' is changed?

**Comment by Tommy0412** [comment]
> Cany you please check the decrypt key '8z5Ag5wgagfsOuhz' is changed?

Key not changed

**Comment by Aijazmakerb** [comment]
> Cany you please check the decrypt key '8z5Ag5wgagfsOuhz' is changed?

Thanks for telling and yes the key had changed but now i updated it
