### ISSUE TITLE
M3u8 link not working 

### ISSUE THREAD

**Issue by rotv123** [Aijazmakerb/vidsrc-api#4]
Nice script mate but the links M3u8 not working anymore any updates?

**Comment by rahuloberai** [comment]
> Nice script mate but the links M3u8 not working anymore any updates?

You need to send rerfer to play video.

**Comment by rotv123** [comment]
> > Nice script mate but the links M3u8 not working anymore any updates?
> 
> You need to send rerfer to play video.
Ohh ok do you have  any ideas how to do this?

**Comment by rahuloberai** [comment]
> > > Nice script mate but the links M3u8 not working anymore any updates?
> 
> > 
> 
> > You need to send rerfer to play video.
> 
> Ohh ok do you have  any ideas how to do this?
> 
> 
> 
> 

Sure, i will update you. 
Please give me some time.

**Comment by rotv123** [comment]
Nice ❤️

**Comment by rahuloberai** [comment]
@tzanta10 
https://hello-world-lively-sun-b454.justchill.workers.dev/?url=https://drbq.v4713144629.site/_v2-wweo/12a3c523f3105800ed8c394685aeeb0b922ea85c02babded4e1a7baea93ece832257df1a4b6125fcfa38c35da05dee86aad28d46d73fc4e9d4e5a1385735a3876fc551f40c16eb0f12c4f6ab6b4622007765d83c57053596cc9ab909cca223863b48e31c/h/list;15a38634f803584ba8926411d7bee906856cab0654b5b8.m3u8&referer=https%3A%2F%2Fe69975b881.nl%2Fe%2FD1YKRQ070PNV
Please have a look

**Comment by rahuloberai** [comment]
> Nice ❤️

Or you can use the proxy server

https://github.com/Gratenes/m3u8CloudflareWorkerProxy

**Comment by rotv123** [comment]
nice  ❤️  can i have yor telegram id please!

**Comment by rahuloberai** [comment]
> nice  ❤️  can i have yor telegram id please!

rahuloberai

**Comment by rotv123** [comment]
thanks

**Comment by tzanta10** [comment]
i need yor help with  https://github.com/Gratenes/m3u8CloudflareWorkerProxy  can you contact me on telegram please!  https://t.me/tzanta

**Comment by emyl1** [comment]
> > Nice ❤️
> 
> Or you can use the proxy server
> 
> https://github.com/Gratenes/m3u8CloudflareWorkerProxy

can you share the worker.js  please!
