### ISSUE TITLE
the API has limited

### ISSUE THREAD

**Issue by dallasrol** [Aijazmakerb/vidsrc-api#6]
{
  "status": 404,
  "return": "Oops reached rate limit of this api"
}

**Comment by Inside4ndroid** [comment]
same happening for me too?

**Comment by Tommy0412** [comment]
keys not updating, https://github.com/Ciarands/vidsrc-keys/blob/main/keys.json
Normaly keys change every hours, but now key extractor which is necessary just not work.

**Comment by Inside4ndroid** [comment]
> keys not updating, https://github.com/Ciarands/vidsrc-keys/blob/main/keys.json Normaly keys change every hours, but now key extractor which is necessary just not work.

is the key extractor source available maybe can help fix it.? if not more info on where these 2 keys come from would be great.

**Comment by Tommy0412** [comment]
> > keys not updating, https://github.com/Ciarands/vidsrc-keys/blob/main/keys.json Normaly keys change every hours, but now key extractor which is necessary just not work.
> 
> is the key extractor source available maybe can help fix it.? if not more info on where these 2 keys come from would be great.

https://github.com/achraf2003/worstsource-keys this is fork of Claudemirovsky repo, which is now deleted.
