### ISSUE TITLE
getting issue

### ISSUE THREAD

**Issue by SamyCodez** [Aijazmakerb/vidsrc-api#7]
from your api 

https://vidsrc-api-two.vercel.app/tt27459160

Result : {"status":404,"return":"Oops media not available"}

but media is available in official website 

https://vidsrc.in/embed/movie?imdb=tt27459160 

please fix it

**Comment by Tommy0412** [comment]
Wrong site, this is vidsrc.to api not vidsrc.me whats difference? Vidsrc.me is oldest, vidsrc to is copycat site.

**Comment by devilxsam** [comment]
> Wrong site, this is vidsrc.to api not vidsrc.me whats difference? Vidsrc.me is oldest, vidsrc to is copycat site.

Any other api for vidsrc.in .vpi etc

**Comment by terabyte-26** [comment]
@devilxsam You can use:
https://github.com/cool-dev-guy/vidsrc-api
